### ISSUE TITLE
Crash when creating text with multiple colors

### ISSUE THREAD

**Issue by Beyley** [FontStashSharp/FontStashSharp#29]
When i try to draw text with multiple colors, it crashes

```cs
public Color[]       ColorArray = new []{Color.LightBlue, Color.Pink, Color.White, Color.Pink};

SpriteBatch.DrawString(
    Font, this.Text, args.Position, this.ColorArray, args.Scale, args.Rotation, Vector2.Zero
);
```

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FontStashSharp.SpriteFontBase.DrawText(IFontStashRenderer renderer, String text, Vector2 position, Color[] colors, Vector2 scale, Single rotation, Vector2 origin, Single layerDepth)
   at FontStashSharp.SpriteFontBase.DrawText(SpriteBatch batch, String text, Vector2 position, Color[] colors, Vector2 scale, Single rotation, Vector2 origin, Single layerDepth)
   at FontStashSharp.SpriteBatchExtensions.DrawString(SpriteBatch batch, SpriteFontBase font, String text, Vector2 position, Color[] colors, Vector2 scale, Single rotation, Vector2 origin, Single layerDepth)
   at Furball.Engine.Engine.Graphics.Drawables.TextDrawable.Draw(GameTime time, DrawableBatch batch, DrawableManagerArgs args) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/Furball/Furball.Engine/Engine/Graphics/Drawables/TextDrawable.cs:line 53
   at Furball.Engine.Engine.Graphics.Drawables.Managers.DrawableManager.Draw(GameTime time, DrawableBatch drawableBatch, DrawableManagerArgs _) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/Furball/Furball.Engine/Engine/Graphics/Drawables/Managers/DrawableManager.cs:line 229
   at Furball.Engine.Engine.Screen.Draw(GameTime gameTime) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/Furball/Furball.Engine/Engine/Screen.cs:line 19
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__116_0(IDrawable drawable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Draw(GameTime gameTime)
   at Furball.Engine.FurballGame.Draw(GameTime gameTime) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/Furball/Furball.Engine/FurballGame.cs:line 321
   at pTyping.pTypingGame.Draw(GameTime gameTime) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/pTyping/pTypingGame.cs:line 238
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at pTyping.Program.Main(String[] args) in /mnt/Home/beyley/Projects/PROGRAMMING/C#/pTyping/pTyping/Program.cs:line 7
```

**Comment by rds1983** [comment]
Should be fixed by #46
