### ISSUE TITLE
Index out of range error from string builder

### ISSUE THREAD

**Issue by bittiez** [FontStashSharp/FontStashSharp#74]
I have players getting this error very frequently, I have not been able to reproduce it myself and I only receive a partial trace.

It looks like it's happening [here](https://github.com/FontStashSharp/FontStashSharp/blob/f11f97b709e50960dd8ce1f727974744c4f8a0dd/src/FontStashSharp/TextSource.cs#L77C22-L77C49), specifically when [`char.IsHighSurrogate(sb[index])`](https://learn.microsoft.com/en-us/dotnet/api/system.char.ishighsurrogate?view=net-7.0) is false and it tries to return the character at the specific index?

## The error
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at FontStashSharp.TextSource.StringBuilderConvertToUtf32(StringBuilder sb, Int32 index) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 80
   at FontStashSharp.TextSource.GetNextCodepoint(Int32&amp; result) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 52
   at FontStashSharp.SpriteFontBase.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 83
   at FontStashSharp.DynamicSpriteFont.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\DynamicSpriteFont.cs:line 223
   at FontStashSharp.SpriteFontBase.TextBounds(StringBuilder text, Vector2 position, Nullable`1 scale, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 143
   ```
   
   Unfortunately I use **FSS** in many different places in an MMO that includes chat from players, so I don't have a way to determine exactly what text may be triggering this, any help is appreciated though!

**Comment by rds1983** [comment]
Can you log all text players write in order to determine what exactly causes the exception?

**Comment by bittiez** [comment]
So these errors are coming from a catch-all unhandled exception, so I don't really know exactly where these are being triggered..
I use FSS RTL inside of a wrapper class called TextBox that is used in many different areas of the game so that would be an immense amount of text to log everything.
From my research it looks like this error occurs on `RTL.Measure()` and `RTL.Update()` when the `LayoutBuilder.Layout` is called, I suppose I could put a temporary try catch there and hope to get something..

Otherwise I will ask and hope one or two of my players will send me their full error log (I only receive a small portion of the full error log)

**Comment by bittiez** [comment]
I was finally able to get a couple reports with the text that caused it but I can't see what would've cause it still:
[log.txt](https://github.com/FontStashSharp/FontStashSharp/files/13395245/log.txt)
[log (1).txt](https://github.com/FontStashSharp/FontStashSharp/files/13395246/log.1.txt)


Those are just using this:
```csharp
	  try
	  {
		_size = _layoutBuilder.Layout(Text, Font, Width);
	  }
	  catch (System.Exception ex)
	  {
		new CrashReportWebhook().SendMessage($"FSS ERROR FROM TEXT: {Text}" + ex.ToString());
	  }
	  ```

**Comment by bittiez** [comment]
I'm getting them more frequently now that it's the weekend, but none of them seem to have any special characters

```csharp
FSS ERROR FROM TEXT: System: Loading WorldMap markers..System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at System.Text.StringBuilder.get_Chars(Int32 index)

   at FontStashSharp.TextSource.StringBuilderConvertToUtf32(StringBuilder sb, Int32 index) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 80

   at FontStashSharp.TextSource.GetNextCodepoint(Int32& result) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 52

   at FontStashSharp.SpriteFontBase.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 83

   at FontStashSharp.DynamicSpriteFont.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\DynamicSpriteFont.cs:line 223

   at FontStashSharp.SpriteFontBase.TextBounds(StringBuilder text, Vector2 position, Nullable`1 scale, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 143

   at FontStashSharp.SpriteFontBase.MeasureString(StringBuilder text, Nullable`1 scale, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 267

   at FontStashSharp.RichText.LayoutBuilder.GetNextChunk(Int32& i, Nullable`1 remainingWidth) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\LayoutBuilder.cs:line 418

   at FontStashSharp.RichText.LayoutBuilder.Layout(String text, SpriteFontBase font, Nullable`1 rowWidth, Boolean measureRun) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\LayoutBuilder.cs:line 543

   at FontStashSharp.RichText.RichTextLayout.Update() in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\RichTextLayout.cs:line 229
   ```
   
   
   ```csharp
   FSS ERROR FROM TEXT: System: Your client is out of date. Please update your client.System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at System.Text.StringBuilder.get_Chars(Int32 index)

   at FontStashSharp.TextSource.StringBuilderConvertToUtf32(StringBuilder sb, Int32 index) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 80

   at FontStashSharp.TextSource.GetNextCodepoint(Int32& result) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\TextSource.cs:line 52

   at FontStashSharp.SpriteFontBase.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 83

   at FontStashSharp.DynamicSpriteFont.InternalTextBounds(TextSource source, Vector2 position, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\DynamicSpriteFont.cs:line 223

   at FontStashSharp.SpriteFontBase.TextBounds(StringBuilder text, Vector2 position, Nullable`1 scale, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 143

   at FontStashSharp.SpriteFontBase.MeasureString(StringBuilder text, Nullable`1 scale, Single characterSpacing, Single lineSpacing, FontSystemEffect effect, Int32 effectAmount) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\SpriteFontBase.cs:line 267

   at FontStashSharp.RichText.LayoutBuilder.GetNextChunk(Int32& i, Nullable`1 remainingWidth) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\LayoutBuilder.cs:line 418

   at FontStashSharp.RichText.LayoutBuilder.Layout(String text, SpriteFontBase font, Nullable`1 rowWidth, Boolean measureRun) in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\LayoutBuilder.cs:line 543

   at FontStashSharp.RichText.RichTextLayout.Update() in C:\Repos\TazUO\external\FontStashSharp\src\FontStashSharp\RichText\RichTextLayout.cs:line 229
   ```
   
I don't want to send too many as none of them have any sort of special characters in them..

**Comment by bittiez** [comment]
Still have these errors rolling in, I don't see any correlation, they all seem to be any random text the client receives.

I wouldn't think it would be an encoding issue as I *think* dotnet stores all stings as UTF16..

**Comment by rds1983** [comment]
That issues could be fixed by this PR: https://github.com/FontStashSharp/FontStashSharp/commit/bdfc72e20756a25edbd890863a6e2cbfe53ffd6a

It fixed how TextChunk.Count was calculated.
Before the fix, it was simply amount of characters, which was wrong and didn't took into account unicode characters.
It even caused IndexOutOfRangeException in my UI library(Myra).
Now the amount of characters should be calculated correctly.

**Comment by bittiez** [comment]
That sounds like it could be the issue, I will get it updated and hopefully that stops the problem 👍

**Comment by bittiez** [comment]
Thanks for the info and help, I will go ahead and close this
